### PR TITLE
fix i32 / u32 uDebug impl for 16-bit pointer width

### LINKED ISSUE #28: Cannot print 32 bit integers
When I try to print a u32 variable above 65535 (`u16::MAX`), the value wraps to a lower value below 65535. This also occurs with i32 overflowing at `i16::MAX`.

I made a reproduction here: [https://github.com/crclark96/ufmt-i32-print-repro](https://github.com/crclark96/ufmt-i32-print-repro), but I'll copy main source file and output below:

```rust
#![no_std]
#![no_main]

extern crate panic_halt;

use arduino_uno::prelude::*;

#[arduino_uno::entry]
fn main() -> ! {
    let dp = arduino_uno::Peripherals::take().unwrap();

    let mut pins = arduino_uno::Pins::new(
        dp.PORTB,
        dp.PORTC,
        dp.PORTD,
    );
    let mut serial = arduino_uno::Serial::new(
        dp.USART0,
        pins.d0,
        pins.d1.into_output(&mut pins.ddr),
        57600.into_baudrate(),
    );

    ufmt::uwriteln!(&mut serial, "unsigned 0..80_000\r").void_unwrap();

    for x in (0u32..80_000u32).step_by(10000) {
        ufmt::uwriteln!(&mut serial, "{}\r", x).void_unwrap();
    }

    ufmt::uwriteln!(&mut serial, "signed 0..80_000\r").void_unwrap();

    for x in (0i32..80_000i32).step_by(10000) {
        ufmt::uwriteln!(&mut serial, "{}\r", x).void_unwrap();
    }

    loop {}
}
```

Output: 

```
unsigned 0..80_000
0
10000
20000
30000
40000
50000
60000
4464
signed 0..80_000
0
10000
20000
30000
-25536
-15536
-5536
4464
```

### PR DESCRIPTION
**Pull request by mrk-its**
fixes #28

### CODE REVIEW

**Comment by mutantbob** [comment]
DOH!  I just spent the past half-hour doing the same thing.  Please merge this so my logging will work.

**Review by japaric — APPROVED** [review]
thanks!

**Comment by japaric** [comment]
bors merge

**Comment by mrk-its** [comment]
thanks!

**Pull request merged**
